# Generated by Django 3.1.5 on 2021-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('definition', models.TextField(max_length=1500)),
                ('source', models.TextField(max_length=5000)),
                ('favorite', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='dictionary.Tag')),
            ],
        ),
    ]
